version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx_logs:/var/log/nginx
    logging:
      driver: "none"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  fluentd:
    build: ./fluentd
    container_name: fluentd
    depends_on:
      - rabbitmq
      - nginx
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./nginx_logs:/var/log/nginx
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.0
    container_name: logstash
    depends_on:
      - rabbitmq
      - elasticsearch
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
      - "9600:9600"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false  # Desabilita a segurança para testes simples
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
